config/routes.rb
SharedTodoApp::Application.routes.draw do
  get "todos/index"
  match 'todos/delete' => 'todos#delete', as: :delete
  match 'todos/add' => 'todos#add', via: :post
  match 'todos/complete' => 'todos#complete', via: :post

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :todo_item, :completed
  validates :todo_item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
    @new_todo = Todo.new
  end
  def delete

  end
  def add
    todo = Todo.create todo_item: params[:todo][:todo_item]
    unless todo.valid?
      flash[:error] = todo.errors.full_messages.join('<br>').html_safe
    else
      flash[:success] = "Todo added successfully!"
    end
    redirect_to action: :index
  end

  def complete
    unless params[:todos_checkbox].nil?
      params[:todos_checkbox].each do |check|
        todo_id = check
        t = Todo.find todo_id
        t.update_attribute(:completed, ! t.completed)
      end
    end
    redirect_to action: 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharedTodoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  <div class="navbar-inner">
    <a class='brand' href="#">Just Did it</a>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/todos/delete.html.erb
<p>Todo successfully delete!</p>
<%= link_to 'Todos', todos_index_path %>

app/views/todos/index.html.erb
<title>Shared Todo App</title>
<div class="container">
  <div class="row">
    <div class="span5">
      <h1>Shared Todo App</h1>
      <hr>
      <p>All your Todos goes here: </p>
      <%= form_for @new_todo, url: { action: 'add' }, html: {  class: 'form-inline' }  do |f| %>
        <%= f.text_field :todo_item, class: 'input-xlarge', placeholder: 'What do you plan to do?' %>
        <%= f.submit 'Add todo', class: 'btn btn-primary' %>
      <% end %>

      <% if flash[:error] %>
        <div class="alert alert-error">
          <button type='button' data-dismiss='alert' class="close">&cross;</button>
          <strong><%= flash[:error] %></strong>
        </div>
      <% end %>

      <% if flash[:success] %>
        <div class="alert alert-success">
          <button type='button' data-dismiss='alert' class="close">&cross;</button>
          <strong><%= flash[:success] %></strong>
        </div>
      <% end %>

      <div class="well">
        <%= form_tag '/todos/complete', method: 'post' do %>
          <ul style='list-style-type:none;'>
            <% @todos.each do |todo| %>
              <% if todo.completed %>
                <li style='color:grey;'><%= check_box_tag 'todos_checkbox[]', todo.id, todo.completed %><strike><%= todo.todo_item %></strike></li>
              <% else %>
                <li><%= check_box_tag 'todos_checkbox[]', todo.id, todo.completed%> <%= todo.todo_item %></li>
              <% end %>
            <% end %>
          </ul>
        <%= submit_tag 'Complete Todos', class: 'btn btn-success' %>
        <% end %>
      </div>
      <%= link_to "Delete last todo", delete_path %>
    </div>
  </div>
</div>